update url and extract strategy

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -11,13 +11,19 @@ source "${plugin_dir}/lib/utils.bash"
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
 # TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+file_ext=$(get_download_file_extension)
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.${file_ext}"
 
-# Download tar.gz file to the download directory
+# Download zip file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+#  Extract contents of zip file into the download directory
+os=$(get_os)
+if [[ $os == "macosx" ]]; then
+    unzip -o "$release_file" -d "$ASDF_DOWNLOAD_PATH" >/dev/null || fail "Could not extract $release_file"
+else
+    tar -xJf "$release_file" -C "$ASDF_DOWNLOAD_PATH" >/dev/null || fail "Could not extract $release_file"
+fi
 
-# Remove the tar.gz file since we don't need to keep it
+# Remove the zip file since we don't need to keep it
 rm "$release_file"
